version: 2.1

commands:
  create_release:
    description: "Creates a release"
    parameters:
      increment_level:
        type: string
        description: "Version level to increment"
    steps:
      - run: sudo apt update && sudo apt install -y gh
      - checkout
      - run: chmod +x ./create_release.sh
      - run:
          command: INCREMENT_LEVEL=<<parameters.increment_level>> ./create_release.sh

jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Installing the linter"
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - run:
          name: "Running the linter"
          command: golangci-lint run
      - run:
          name: "Testing the code"
          command: go test ./... -cover
  release_major:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    resource_class: small
    steps:
      - create_release:
          increment_level: major
  release_minor:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    resource_class: small
    steps:
      - create_release:
          increment_level: minor
  release_patch:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    resource_class: small
    steps:
      - create_release:
          increment_level: patch
workflows:
  version: 2
  tests_and_release:
    jobs:
      - tests_approval:
          type: approval
      - tests:
          requires:
            - tests_approval
      - release_major_approval:
          type: approval
          filters:
            branches:
              only: main
      - release_minor_approval:
          type: approval
          filters:
            branches:
              only: main
      - release_patch_approval:
          type: approval
          filters:
            branches:
              only: main
      - release_major:
          requires:
            - release_major_approval
            - tests
          filters:
            branches:
              only: main
      - release_minor:
          requires:
            - release_minor_approval
            - tests
          filters:
            branches:
              only: main
      - release_patch:
          requires:
            - release_patch_approval
            - tests
          filters:
            branches:
              only: main
