version: 2.1
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Installing the linter"
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - run:
          name: "Running the linter"
          command: golangci-lint run
      - run:
          name: "Testing the code"
          command: go test ./... -cover
  release_approval:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: Hold for approval
          command: |
            echo "Pipeline is on hold until approval received"
  release:
    docker:
      - image: cimg/go:1.19
    steps:
      - run: sudo apt update && sudo apt install -y gh
      - checkout
      - run: ./create_release.sh
workflows:
  version: 2
  tests_and_release:
    jobs:
      - tests:
          filters:
            branches:
              ignore: master
      - approval:
          type: approval
          requires:
            - tests_on_master
      - release:
          requires:
            - approval
