version: 2.1
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Installing the linter"
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - run:
          name: "Running the linter"
          command: golangci-lint run
      - run:
          name: "Testing the code"
          command: go test ./... -cover
  release:
    docker:
      - image: cimg/go:1.19
    steps:
      - run: sudo apt update && sudo apt install -y gh
      - checkout
      - run: ./create_release.sh
workflows:
  version: 2
  test-and-release:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - tests
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/